facebook:
  label: Facebook
  permalink: /facebook
  description: Facebook tag description

hello:
  label: Hello
  permalink: /hello
  description: Hello tag description

docusaurus:
  label: Docusaurus
  permalink: /docusaurus
  description: Docusaurus tag description

hola:
  label: Hola
  permalink: /hola
  description: Hola tag description

cybersecurity:
  label: Cybersecurity
  permalink: /cybersecurity
  description: Wszystko o bezpieczeństwie IT i cyberzagrożeniach.

automation:
  label: Automation
  permalink: /automation
  description: Automatyzacja procesów, testów i przepływów pracy.

esp32:
  label: ESP32
  permalink: /esp32
  description: Projekty i poradniki związane z mikrokontrolerem ESP32.

web-security:
  label: Web Security
  permalink: /web-security
  description: Praktyki, narzędzia i techniki zabezpieczania aplikacji webowych.

playwright:
  label: Playwright
  permalink: /playwright
  description: Testowanie end-to-end z wykorzystaniem Playwright.

typescript:
  label: TypeScript
  permalink: /typescript
  description: Typowany JavaScript dla skalowalnych aplikacji.

networking:
  label: Networking
  permalink: /networking
  description: Konfiguracja sieci, bezpieczeństwo i narzędzia diagnostyczne.

raspberry-pi:
  label: Raspberry Pi
  permalink: /raspberry-pi
  description: Projekty, poradniki i zastosowania Raspberry Pi.

iot:
  label: IoT
  permalink: /iot
  description: Internet Rzeczy — budowa systemów IoT i integracje.

github-pages:
  label: GitHub Pages
  permalink: /github-pages
  description: Hostowanie stron statycznych z użyciem GitHub Pages.

angular:
  label: Angular
  permalink: /angular
  description: Framework do budowy aplikacji SPA.

firebase:
  label: Firebase
  permalink: /firebase
  description: Backend-as-a-Service dla aplikacji webowych i mobilnych.

seo:
  label: SEO
  permalink: /seo
  description: Optymalizacja stron internetowych pod kątem wyszukiwarek.

ci-cd:
  label: CI/CD
  permalink: /ci-cd
  description: Automatyzacja procesu buildowania, testowania i wdrażania aplikacji.

linux:
  label: Linux
  permalink: /linux
  description: Komendy, skrypty i konfiguracje dla systemów Linux.

pihole:
  label: Pi-hole
  permalink: /pihole
  description: Blokowanie reklam i ochrona sieci przy użyciu Pi-hole.

vaultwarden:
  label: Vaultwarden
  permalink: /vaultwarden
  description: Samodzielnie hostowany menedżer haseł oparty na Bitwarden.

yubikey:
  label: YubiKey
  permalink: /yubikey
  description: Uwierzytelnianie dwuskładnikowe za pomocą klucza sprzętowego YubiKey.

issa-polska:
  label: ISSA Polska
  permalink: /issa-polska
  description: Społeczność ISSA Polska.

społeczność:
  label: Społeczność
  permalink: /spolecznosc
  description: Wydarzenia, spotkania i inicjatywy społecznościowe.

jamming:
  label: Jamming
  permalink: /jamming
  description: Zakłócanie sygnałów radiowych i techniki przeciwdziałania.

xiaomi:
  label: Xiaomi
  permalink: /xiaomi
  description: Urządzenia i technologie Xiaomi.

ochrona-sieci:
  label: Ochrona Sieci
  permalink: /ochrona-sieci
  description: Techniki i narzędzia ochrony sieci komputerowych.

browser:
  label: Browser
  permalink: /browser
  description: Przeglądarki internetowe i ich rozszerzenia.

extensions:
  label: Extensions
  permalink: /extensions
  description: Rozszerzenia przeglądarek internetowych.

adblock:
  label: Adblock
  permalink: /adblock
  description: Blokowanie reklam w przeglądarkach internetowych.

privacy:
  label: Privacy
  permalink: /privacy
  description: Ochrona prywatności w sieci.

esp-idf:
  label: ESP-IDF
  permalink: /esp-idf
  description: Framework do programowania mikrokontrolerów ESP32.

arduino:
  label: Arduino
  permalink: /arduino
  description: Platforma do prototypowania elektroniki.

platformio:
  label: PlatformIO
  permalink: /platformio
  description: Ekosystem do programowania mikrokontrolerów.

micropython:
  label: MicroPython
  permalink: /micropython
  description: Implementacja Pythona dla mikrokontrolerów.

circuitpython:
  label: CircuitPython
  permalink: /circuitpython
  description: Implementacja Pythona dla mikrokontrolerów.

esphome:
  label: ESPHome
  permalink: /esphome
  description: Framework do automatyzacji domowej z użyciem ESP32.

tasmota:
  label: Tasmota
  permalink: /tasmota
  description: Oprogramowanie open-source dla urządzeń IoT.

zephyr-rtos:
  label: Zephyr RTOS
  permalink: /zephyr-rtos
  description: System operacyjny czasu rzeczywistego dla mikrokontrolerów.

tutorial:
  label: Tutorial
  permalink: /tutorial
  description: Poradniki i instrukcje krok po kroku.

testing:
  label: Testing
  permalink: /testing
  description: Testowanie oprogramowania.

istqb:
  label: ISTQB
  permalink: /istqb
  description: Certyfikacja ISTQB.

certification:
  label: Certification
  permalink: /certification
  description: Certyfikacje i egzaminy.

software-testing:
  label: Software Testing
  permalink: /software-testing
  description: Testowanie oprogramowania.

terminal:
  label: Terminal
  permalink: /terminal
  description: Zarządzanie terminalem i jego historia.

history:
  label: History
  permalink: /history
  description: Historia i zarządzanie.

management:
  label: Management
  permalink: /management
  description: Zarządzanie i organizacja.

atuin:
  label: Atuin
  permalink: /atuin
  description: Narzędzie do zarządzania historią terminala.

bezpieczeństwo:
  label: Bezpieczeństwo
  permalink: /bezpieczenstwo
  description: Poradniki dotyczące bezpieczeństwa.

sieć:
  label: Sieć
  permalink: /siec
  description: Poradniki dotyczące sieci komputerowych.

poradnik:
  label: Poradnik
  permalink: /poradnik
  description: Instrukcje krok po kroku.

drony:
  label: Drony
  permalink: /drony
  description: Technologie dronów i UAV.

wojsko:
  label: Wojsko
  permalink: /wojsko
  description: Technologie wojskowe.

technologie:
  label: Technologie
  permalink: /technologie
  description: Nowoczesne technologie.

uav:
  label: UAV
  permalink: /uav
  description: Bezzałogowe statki powietrzne.

bsp:
  label: BSP
  permalink: /bsp
  description: Bezzałogowe systemy powietrzne.

iso27002:
  label: ISO27002
  permalink: /iso27002
  description: Standardy bezpieczeństwa informacji zgodne z ISO27002.

bezpieczeństwo-informacji:
  label: Bezpieczeństwo Informacji
  permalink: /bezpieczenstwo-informacji
  description: Ochrona i zarządzanie bezpieczeństwem informacji.

standardy-międzynarodowe:
  label: Standardy Międzynarodowe
  permalink: /standardy-miedzynarodowe
  description: Międzynarodowe standardy i normy.

zarządzanie-bezpieczeństwem:
  label: Zarządzanie Bezpieczeństwem
  permalink: /zarzadzanie-bezpieczenstwem
  description: Zarządzanie bezpieczeństwem w organizacjach.

it:
  label: IT
  permalink: /it
  description: Technologie informacyjne i ich zastosowania.

dokumentacja:
  label: Dokumentacja
  permalink: /dokumentacja
  description: Dokumentacja techniczna i użytkowa.

military:
  label: Military
  permalink: /military
  description: Technologie wojskowe i obronne.

communication:
  label: Communication
  permalink: /communication
  description: Technologie komunikacyjne i ich zastosowania.

link-16:
  label: Link 16
  permalink: /link-16
  description: Systemy komunikacji Link 16.

nato:
  label: NATO
  permalink: /nato
  description: Organizacja Traktatu Północnoatlantyckiego i jej działania.
