facebook:
  label: Facebook
  permalink: /facebook
  description: Facebook tag description

hello:
  label: Hello
  permalink: /hello
  description: Hello tag description
  
docusaurus:
  label: Docusaurus
  permalink: /docusaurus
  description: Docusaurus tag description

hola:
  label: Hola
  permalink: /hola
  description: Hola tag description

cybersecurity:
  label: Cybersecurity
  permalink: /cybersecurity
  description: Wszystko o bezpieczeństwie IT i cyberzagrożeniach.

secops:
  label: SecOps
  permalink: /secops
  description: Operacje bezpieczeństwa, monitorowanie i reagowanie na incydenty.

bash-scripting:
  label: Bash Scripting
  permalink: /bash-scripting
  description: Skrypty, one-linery i automatyzacja z użyciem Basha.

black-hat-bash:
  label: Black Hat Bash
  permalink: /black-hat-bash
  description: Materiały i przykłady związane z książką Black Hat Bash i taktykami Basha.

port-scanning:
  label: Port Scanning
  permalink: /port-scanning
  description: Techniki skanowania portów, narzędzia i analiza wyników.

rustscan:
  label: RustScan
  permalink: /rustscan
  description: Artykuły i przykłady użycia RustScan do szybkiego skanowania.

red-teaming:
  label: Red Teaming
  permalink: /red-teaming
  description: Taktiki, narzędzia i ćwiczenia dla zespołów Red Team.

book-review:
  label: Book Review
  permalink: /book-review
  description: Recenzje książek technicznych i branżowych.

black-hat-python:
  label: Black Hat Python
  permalink: /black-hat-python
  description: Materiały i recenzje dotyczące Black Hat Python i podobnych pozycji.

python:
  label: Python
  permalink: /python
  description: Artykuły i poradniki dotyczące języka Python.

offensive-security:
  label: Offensive Security
  permalink: /offensive-security
  description: Techniki ofensywne, narzędzia i badania z zakresu bezpieczeństwa ofensywnego.

security:
  label: Security
  permalink: /security
  description: Ochrona danych, systemów i sieci komputerowych.

automation:
  label: Automation
  permalink: /automation
  description: Automatyzacja procesów, testów i przepływów pracy.

esp32:
  label: ESP32
  permalink: /esp32
  description: Projekty i poradniki związane z mikrokontrolerem ESP32.

web-security:
  label: Web Security
  permalink: /web-security
  description: Praktyki, narzędzia i techniki zabezpieczania aplikacji webowych.

playwright:
  label: Playwright
  permalink: /playwright
  description: Testowanie end-to-end z wykorzystaniem Playwright.

typescript:
  label: TypeScript
  permalink: /typescript
  description: Typowany JavaScript dla skalowalnych aplikacji.

networking:
  label: Networking
  permalink: /networking
  description: Konfiguracja sieci, bezpieczeństwo i narzędzia diagnostyczne.

raspberry-pi:
  label: Raspberry Pi
  permalink: /raspberry-pi
  description: Projekty, poradniki i zastosowania Raspberry Pi.

iot:
  label: IoT
  permalink: /iot
  description: Internet Rzeczy — budowa systemów IoT i integracje.

github-pages:
  label: GitHub Pages
  permalink: /github-pages
  description: Hostowanie stron statycznych z użyciem GitHub Pages.

angular:
  label: Angular
  permalink: /angular
  description: Framework do budowy aplikacji SPA.

firebase:
  label: Firebase
  permalink: /firebase
  description: Backend-as-a-Service dla aplikacji webowych i mobilnych.

seo:
  label: SEO
  permalink: /seo
  description: Optymalizacja stron internetowych pod kątem wyszukiwarek.

ci-cd:
  label: CI/CD
  permalink: /ci-cd
  description: Automatyzacja procesu buildowania, testowania i wdrażania aplikacji.

linux:
  label: Linux
  permalink: /linux
  description: Komendy, skrypty i konfiguracje dla systemów Linux.

pihole:
  label: Pi-hole
  permalink: /pihole
  description: Blokowanie reklam i ochrona sieci przy użyciu Pi-hole.

gps:
  label: GPS
  permalink: /gps
  description: Systemy nawigacji satelitarnej, technologie GPS i ich zastosowania.

spoofing:
  label: Spoofing
  permalink: /spoofing
  description: Techniki podszywania się pod inne urządzenia lub sygnały.

nawigacja:
  label: Nawigacja
  permalink: /nawigacja
  description: Systemy i technologie nawigacyjne, zarówno satelitarne, jak i tradycyjne.

open-source-intel:
  label: Open Source Intel
  permalink: /open-source-intel
  description: Analiza i wykorzystanie otwartych źródeł informacji (OSINT).

vaultwarden:
  label: Vaultwarden
  permalink: /vaultwarden
  description: Samodzielnie hostowany menedżer haseł oparty na Bitwarden.

yubikey:
  label: YubiKey
  permalink: /yubikey
  description: Uwierzytelnianie dwuskładnikowe za pomocą klucza sprzętowego YubiKey.

issa-polska:
  label: ISSA Polska
  permalink: /issa-polska
  description: Społeczność ISSA Polska.

społeczność:
  label: Społeczność
  permalink: /spolecznosc
  description: Wydarzenia, spotkania i inicjatywy społecznościowe.

jamming:
  label: Jamming
  permalink: /jamming
  description: Zakłócanie sygnałów radiowych i techniki przeciwdziałania.

xiaomi:
  label: Xiaomi
  permalink: /xiaomi
  description: Urządzenia i technologie Xiaomi.

ochrona-sieci:
  label: Ochrona Sieci
  permalink: /ochrona-sieci
  description: Techniki i narzędzia ochrony sieci komputerowych.

browser:
  label: Browser
  permalink: /browser
  description: Przeglądarki internetowe i ich rozszerzenia.

extensions:
  label: Extensions
  permalink: /extensions
  description: Rozszerzenia przeglądarek internetowych.

adblock:
  label: Adblock
  permalink: /adblock
  description: Blokowanie reklam w przeglądarkach internetowych.

privacy:
  label: Privacy
  permalink: /privacy
  description: Ochrona prywatności w sieci.

esp-idf:
  label: ESP-IDF
  permalink: /esp-idf
  description: Framework do programowania mikrokontrolerów ESP32.

arduino:
  label: Arduino
  permalink: /arduino
  description: Platforma do prototypowania elektroniki.

platformio:
  label: PlatformIO
  permalink: /platformio
  description: Ekosystem do programowania mikrokontrolerów.

micropython:
  label: MicroPython
  permalink: /micropython
  description: Implementacja Pythona dla mikrokontrolerów.

circuitpython:
  label: CircuitPython
  permalink: /circuitpython
  description: Implementacja Pythona dla mikrokontrolerów.

esphome:
  label: ESPHome
  permalink: /esphome
  description: Framework do automatyzacji domowej z użyciem ESP32.

tasmota:
  label: Tasmota
  permalink: /tasmota
  description: Oprogramowanie open-source dla urządzeń IoT.

zephyr-rtos:
  label: Zephyr RTOS
  permalink: /zephyr-rtos
  description: System operacyjny czasu rzeczywistego dla mikrokontrolerów.

tutorial:
  label: Tutorial
  permalink: /tutorial
  description: Poradniki i instrukcje krok po kroku.

testing:
  label: Testing
  permalink: /testing
  description: Testowanie oprogramowania.

istqb:
  label: istqb
  permalink: /istqb
  description: Certyfikacja ISTQB.

certification:
  label: Certification
  permalink: /certification
  description: Certyfikacje i egzaminy.

software-testing:
  label: Software Testing
  permalink: /software-testing
  description: Testowanie oprogramowania.

terminal:
  label: Terminal
  permalink: /terminal
  description: Zarządzanie terminalem i jego historia.

history:
  label: History
  permalink: /history
  description: Historia i zarządzanie.

management:
  label: Management
  permalink: /management
  description: Zarządzanie i organizacja.

atuin:
  label: Atuin
  permalink: /atuin
  description: Narzędzie do zarządzania historią terminala.

bezpieczeństwo:
  label: Bezpieczeństwo
  permalink: /bezpieczenstwo
  description: Poradniki dotyczące bezpieczeństwa.

sieć:
  label: Sieć
  permalink: /siec
  description: Poradniki dotyczące sieci komputerowych.

poradnik:
  label: Poradnik
  permalink: /poradnik
  description: Instrukcje krok po kroku.

drony:
  label: Drony
  permalink: /drony
  description: Technologie dronów i UAV.

wojsko:
  label: Wojsko
  permalink: /wojsko
  description: Technologie wojskowe.

technologie:
  label: Technologie
  permalink: /technologie
  description: Nowoczesne technologie.

uav:
  label: UAV
  permalink: /uav
  description: Bezzałogowe statki powietrzne.

bsp:
  label: BSP
  permalink: /bsp
  description: Bezzałogowe systemy powietrzne.

iso27002:
  label: ISO27002
  permalink: /iso27002
  description: Standardy bezpieczeństwa informacji zgodne z ISO27002.

bezpieczenstwo-informacji:
  label: Bezpieczeństwo Informacji
  permalink: /bezpieczenstwo-informacji
  description: Ochrona i zarządzanie bezpieczeństwem informacji.

standardy-miedzynarodowe:
  label: Standardy Międzynarodowe
  permalink: /standardy-miedzynarodowe
  description: Międzynarodowe standardy i normy.

zarzadzanie-bezpieczeństwem:
  label: Zarządzanie Bezpieczeństwem
  permalink: /zarzadzanie-bezpieczenstwem
  description: Zarządzanie bezpieczeństwem w organizacjach.

it:
  label: IT
  permalink: /it
  description: Technologie informacyjne i ich zastosowania.

dokumentacja:
  label: Dokumentacja
  permalink: /dokumentacja
  description: Dokumentacja techniczna i użytkowa.

military:
  label: Military
  permalink: /military
  description: Technologie wojskowe i obronne.

communication:
  label: Communication
  permalink: /communication
  description: Technologie komunikacyjne i ich zastosowania.

link-16:
  label: Link 16
  permalink: /link-16
  description: Systemy komunikacji Link 16.

nato:
  label: NATO
  permalink: /nato
  description: Organizacja Traktatu Północnoatlantyckiego i jej działania.

webapp:
  label: Web Application
  permalink: /webapp
  description: Aplikacje webowe i ich bezpieczeństwo.

pentesting:
  label: Penetration Testing
  permalink: /pentesting
  description: Testowanie penetracyjne i techniki zabezpieczeń.

owasp:
  label: OWASP
  permalink: /owasp
  description: Open Web Application Security Project i jego wytyczne.

cyberbezpieczenstwo:
  label: Cyberbezpieczeństwo
  permalink: /cyberbezpieczenstwo
  description: Wszystko o cyberbezpieczeństwie.

malware:
  label: Malware
  permalink: /malware
  description: Złośliwe oprogramowanie i techniki obrony.
wydarzenia:
  label: Wydarzenia
  permalink: /wydarzenia
  description: Spotkania, eventy i wydarzenia branżowe.

konferencje:
  label: Konferencje
  permalink: /konferencje
  description: Konferencje technologiczne i branżowe.

ransomware:
  label: Ransomware
  permalink: /ransomware
  description: Ataki ransomware i metody ochrony.

vulnerabilities:
  label: Vulnerabilities
  permalink: /vulnerabilities
  description: Luki bezpieczeństwa i raporty o podatnościach.

exploits:
  label: Exploits
  permalink: /exploits
  description: Eksploity i techniki wykorzystania podatności.

osint:
  label: OSINT
  permalink: /osint
  description: Open-source intelligence — techniki zbierania informacji z publicznych źródeł.

analiza:
  label: Analiza
  permalink: /analiza
  description: Analiza techniczna, raporty i case studies.

phoneinfoga:
  label: PhoneInfoga
  permalink: /phoneinfoga
  description: Narzędzie PhoneInfoga i techniki analizy numerów telefonów.

intelx:
  label: IntelX
  permalink: /intelx
  description: Platforma IntelX i metody wyszukiwania informacji.

grupy-hakerskie:
  label: Grupy Hakerskie
  permalink: /grupy-hakerskie
  description: Analiza grup hakerskich i ich działań.

ataki:
  label: Ataki
  permalink: /ataki
  description: Techniki ataków i metody obrony.

securityengineer:
  label: Security Engineer
  permalink: /securityengineer
  description: Rola i porady dla inżynierów bezpieczeństwa.

przewodnik:
  label: Przewodnik
  permalink: /przewodnik
  description: Poradniki i przewodniki krok po kroku.

certyfikaty:
  label: Certyfikaty
  permalink: /certyfikaty
  description: Informacje o certyfikatach i procesie certyfikacji.

aiact:
  label: AI & ACT
  permalink: /aiact
  description: Tematy związane z AI w bezpieczeństwie (skrótowa kategoria).

game-dev:
  label: Game Dev
  permalink: /game-dev
  description: Tworzenie gier i aktualizacje dotyczące projektów game-dev.

falconsescape:
  label: Falcons Escape
  permalink: /falconsescape
  description: Tag specyficzny dla gry/projektu Falcons Escape.

n8n:
  label: n8n
  permalink: /n8n
  description: Automatyzacja workflowów przy użyciu n8n.

fedora:
  label: Fedora
  permalink: /fedora
  description: Poradniki i artykuły związane z dystrybucją Fedora.

aiSeo:
  label: AI SEO
  permalink: /ai-seo
  description: Zastosowania AI w SEO i optymalizacji treści.

geo:
  label: Geo
  permalink: /geo
  description: Geolokalizacja i narzędzia geoinformacyjne.

generativeAI:
  label: Generative AI
  permalink: /generative-ai
  description: Generatywne modele AI i ich zastosowania.

answerEngineOptimization:
  label: Answer Engine Optimization
  permalink: /answer-engine-optimization
  description: Optymalizacja treści pod wyszukiwarki odpowiedzi.

AIsecurity:
  label: AI Security
  permalink: /ai-security
  description: Bezpieczeństwo systemów wykorzystujących AI.

genAI:
  label: Generative AI
  permalink: /gen-ai
  description: Generatywna sztuczna inteligencja.

artificialIntelligence:
  label: Artificial Intelligence
  permalink: /artificial-intelligence
  description: Ogólne tematy związane ze sztuczną inteligencją.

cyberThreats:
  label: Cyber Threats
  permalink: /cyber-threats
  description: Zagrożenia i incydenty cybernetyczne.

dataBreach:
  label: Data Breach
  permalink: /data-breach
  description: Incydenty wycieków danych i analiza skutków.

promptInjection:
  label: Prompt Injection
  permalink: /prompt-injection
  description: Ataki na modele językowe i manipulacje promptami.

deepfake:
  label: Deepfake
  permalink: /deepfake
  description: Fałszywe treści multimedialne i ich wykrywanie.

zeroDay:
  label: Zero Day
  permalink: /zero-day
  description: Luki zero-day i raporty o nowych exploitach.

infosec:
  label: Infosec
  permalink: /infosec
  description: Informacje o bezpieczeństwie informacji.

MLsecurity:
  label: ML Security
  permalink: /ml-security
  description: Bezpieczeństwo modeli uczenia maszynowego.

securityAwareness:
  label: Security Awareness
  permalink: /security-awareness
  description: Edukacja i podnoszenie świadomości na temat bezpieczeństwa.

techRisks:
  label: Tech Risks
  permalink: /tech-risks
  description: Ryzyka technologiczne i ich ocena.

AIexploit:
  label: AI Exploit
  permalink: /ai-exploit
  description: Wykorzystania słabości w systemach AI.

secureAI:
  label: Secure AI
  permalink: /secure-ai
  description: Projektowanie bezpiecznych systemów AI.

patchManagement:
  label: Patch Management
  permalink: /patch-management
  description: Zarządzanie poprawkami i aktualizacjami.

cyberIncident:
  label: Cyber Incident
  permalink: /cyber-incident
  description: Reagowanie na incydenty i procesy ich obsługi.

threat-intelligence:
  label: Threat Intelligence
  permalink: /threat-intelligence
  description: Zbieranie i analiza informacji o zagrożeniach.

iso27001:
  label: ISO27001
  permalink: /iso27001
  description: Standard ISO/IEC 27001 dotyczący zarządzania bezpieczeństwem informacji.

contentMarketing:
  label: Content Marketing
  permalink: /blog/tags/contentMarketing
  description: Tworzenie i dystrybucja treści mających na celu przyciąganie i angażowanie odbiorców.

searchAI:
  label: Search AI
  permalink: /blog/tags/searchAI
  description: Sztuczna inteligencja w systemach wyszukiwawczych i rankingach wyników.

schemaMarkup:
  label: Schema Markup
  permalink: /blog/tags/schemaMarkup
  description: Strukturalne dane (schema.org) i ich zastosowanie w SEO.

technicalSEO:
  label: Technical SEO
  permalink: /blog/tags/technicalSEO
  description: Techniczne aspekty optymalizacji indeksacja, sitemapy, wydajność i crawlability.

eEAT:
  label: eEAT
  permalink: /blog/tags/eEAT
  description: E-E-A-T doświadczenie, ekspertyza, autorytet i wiarygodność treści.

featuredSnippets:
  label: Featured Snippets
  permalink: /blog/tags/featuredSnippets
  description: Optymalizacja treści pod fragmenty wyróżnione w wynikach wyszukiwania.

voiceSearch:
  label: Voice Search
  permalink: /blog/tags/voiceSearch
  description: Optymalizacja treści pod wyszukiwanie głosowe i interakcje głosowe.

contentStrategy:
  label: Content Strategy
  permalink: /blog/tags/contentStrategy
  description: Planowanie, tworzenie i zarządzanie treścią długoterminowo.

digitalPR:
  label: Digital PR
  permalink: /blog/tags/digitalPR
  description: Public relations w kanałach cyfrowych i budowanie zasięgu online.

brandAuthority:
  label: Brand Authority
  permalink: /blog/tags/brandAuthority
  description: Budowanie autorytetu marki i jej reputacji w sieci.

aiTools:
  label: AI Tools
  permalink: /blog/tags/aiTools
  description: Narzędzia i platformy oparte na sztucznej inteligencji.

openai:
  label: OpenAI
  permalink: /blog/tags/openai
  description: Technologie i projekty związane z OpenAI.

perplexity:
  label: Perplexity
  permalink: /blog/tags/perplexity
  description: Wpisy dotyczące narzędzia Perplexity i podobnych rozwiązań.

multimodalSearch:
  label: Multimodal Search
  permalink: /blog/tags/multimodalSearch
  description: Wyszukiwanie multimodalne (tekst, obraz, dźwięk) i jego praktyczne zastosowania.

cors:
  label: CORS
  permalink: /cors
  description: Cross-Origin Resource Sharing i powiązane zagadnienia, weryfikacja Origin.

samesite:
  label: SameSite
  permalink: /samesite
  description: Mechanizm atrybutu SameSite dla ciasteczek (Lax, Strict, None) i zabezpieczenia.

http:
  label: HTTP
  permalink: /http
  description: Podstawy protokołu HTTP i jego mechanizmy.

http2:
  label: HTTP/2
  permalink: /http2
  description: Wersja 2 protokołu HTTP, ramkowanie binarne i multipleksowanie.

http3:
  label: HTTP/3
  permalink: /http3
  description: Wersja 3 protokołu HTTP oparta na QUIC.

tls:
  label: TLS
  permalink: /tls
  description: Transport Layer Security i szyfrowanie połączeń.

quic:
  label: QUIC
  permalink: /quic
  description: Bezpieczny i wydajny protokół transportowy oparty na UDP.

crlf:
  label: CRLF
  permalink: /crlf
  description: Wstrzykiwanie znaków powrotu karetki i nowej linii.